datasets:
  batch_size: 256
  data_type: multi
  fix_asym: false
  permute_dataset: false
  seed:
  use_cuda: false
model_params:
  agents_params:
    cell_type: '<class ''torch.nn.modules.rnn.RNN''>'
    dropout: 0
    n_agents: 2
    n_hid: 100
    n_in: 784
    n_ins:
    n_layer: 1
    n_out: 10
    train_in_out:
      - true
      - false
    use_bottleneck: false
    use_readout: true
  global_rewire: false
  use_deepR: false
optimization:
  agents:
    gamma: 0.9
    lr: 0.001
  connections:
    cooling: 0.95
    gamma: 0.95
    gdnoise: 0.0001
    l1: 0.0001
    lr: 0.1
p_cons_params:
  - 0.0001
  - 0.999
  - 10
saves:
  metrics_save_path: /home/gb21/Code/ANNs/community-of-agents/wandb/run-20220428_224604-3016w7uh/files/metrics/
  models_save_name: Community_State_Dicts_10
  models_save_path: /home/gb21/Code/ANNs/community-of-agents/wandb/run-20220428_224604-3016w7uh/files/state_dicts/
task: parity_digits
training:
  decision_params:
    - last
    - max
  early_stop: true
  inverse_task: false
  n_epochs: 15
  n_tests: 5
