datasets:
  batch_size: 256
  common_input: true
  data_sizes:
  data_type: symbols
  fix_asym: false
  input_size: 3600
  n_classes: 16
  n_classes_per_digit: 8
  permute_dataset: false
  seed:
  symbol_config:
    adjust_probas: false
    data_size:
      - 60000
      - 10000
    input_size: 60
    n_diff_symbols: 2
    n_symbols: 15
    nb_steps: 10
    parallel: false
    static: true
    symbol_type: mod_5
  use_cuda: false
debug_run: false
metrics:
  chosen_timesteps:
    - mid-
    - last
metrics_only: false
model:
  agents:
    ag_dropout: 0.0
    cell_type: '<class ''torch.nn.modules.rnn.RNN''>'
    n_hidden: 20
    n_in: 3600
    n_layers: 1
    n_out: 8
    n_readouts: 1
    train_in_out:
      - true
      - true
    use_bottleneck: false
  common_readout: false
  connections:
    binarize: false
    comms_dropout: 0.0
    comms_out_scale: 0.1
    comms_start: start
    sparsity: 0.01
    use_deepR: false
  n_agents: 2
  n_ins:
  n_readouts: 1
  readout_from:
  readout_n_hid:
n_tests: 5
optimization:
  agents:
    gamma: 0.95
    lr: 0.001
    reg_readout:
  connections:
    cooling: 0.95
    gamma: 0.95
    gdnoise: 0.001
    global_rewire: false
    l1: 1.0e-05
    lr: 0.001
task: bitxor
training:
  decision:
    - last
    - all
  early_stop: false
  force_connections: false
  inverse_task: false
  n_epochs: 30
  stopping_acc: 0.95
use_tqdm: false
varying_params_local: {}
varying_params_sweep: {}
