datasets:
  batch_size: 256
  data_type: symbols
  fix_asym: false
  input_size: 3600
  n_classes: 20
  n_classes_per_digit: 10
  permute_dataset: false
  seed:
  symbol_config:
    adjust_probabilites: false
    common_input: true
    data_size:
      - 10000
      - 2000
    input_size: 60
    n_diff_symbols: 2
    n_symbols: 19
    nb_steps: 10
    parallel: false
    static: true
    symbol_type: mod_5
  use_cuda: true
debug_run: true
metrics:
  chosen_timesteps:
    - mid-
    - last
metrics_only: false
model:
  agents:
    ag_dropout: 0.0
    cell_type: '<class ''torch.nn.modules.rnn.RNN''>'
    n_hidden: 20
    n_in: 3600
    n_layers: 1
    train_in_out:
      - true
      - true
    use_bottleneck: false
  connections:
    binarize: false
    comms_dropout: 0.0
    comms_out_scale: 0.1
    comms_start: start
    sparsity: 0.01
    use_deepR: false
  n_agents: 2
  n_ins:
  readout:
    common_readout: true
    n_hid:
    readout_from:
n_tests: 2
optimization:
  agents:
    gamma: 0.95
    lr: 0.001
    reg_readout:
  connections:
    cooling: 0.95
    gamma: 0.95
    gdnoise: 0.001
    global_rewire: false
    l1: 1.0e-05
    lr: 0.001
task: count-max
training:
  decision:
    - last
    - all
  early_stop: false
  force_connections: false
  inverse_task: false
  n_epochs: 1
  stopping_acc: 0.95
use_tqdm: true
varying_params: {}
