data_regen:
  - false
  - true
datasets:
  batch_size: 512
  common_input: true
  cov_ratio: 1.0
  data_size:
  data_type: double_d
  fix_asym: false
  input_size: 1568
  n_classes: 20
  n_classes_per_digit: 10
  n_digits: 2
  nb_steps: 2
  permute_dataset: true
  seed: 51
  split_classes: false
  symbol_config: {}
  use_cuda: true
debug_run: false
metrics:
  chosen_timesteps:
    - mid-
    - last
metrics_only: false
model:
  agents:
    ag_dropout: 0.0
    cell_type: '<class ''torch.nn.modules.rnn.RNN''>'
    n_bot: 5
    n_hidden: 20
    n_in: 1568
    n_layers: 1
    train_in_out:
      - true
      - true
  connections:
    binarize: false
    comms_dropout: 0.0
    comms_out_scale: 1
    comms_start: start
    global_rewire: false
    sparsity: 0.1
    use_deepR: false
  n_agents: 2
  readout:
    common_readout: true
    n_hid:
    readout_from:
n_tests: 5
optimization:
  agents:
    gamma: 0.92
    lr: 0.001
    reg_readout:
  connections:
    cooling: 0.95
    gamma: 0.95
    gdnoise: 0.001
    global_rewire: false
    l1: 1.0e-05
    lr: 0.001
sweep_id:
task: parity-digits
training:
  check_gradients: false
  decision:
    - last
    - all
  early_stop: false
  force_connections: false
  inverse_task: false
  n_epochs: 25
  stopping_acc: 0.95
use_tqdm: 2
varying_params_local: {}
varying_params_sweep: {}
wandb_log: false
