data_regen:
  - false
  - false
datasets:
  batch_size: 512
  common_input: false
  cov_ratio: 1.0
  data_size:
    - 6000
    - 1000
  data_type: double_digits
  fix_asym: false
  input_size: 784
  n_classes: 32
  n_classes_per_digit: 16
  n_digits: 2
  nb_steps: 3
  permute_dataset: true
  seed: 36
  split_classes: true
  symbol_config:
    adjust_probas: false
    data_size:
      - 12000
      - 2000
    input_size: 60
    parallel: false
    random_transform: true
    static: true
    symbol_type: mod_5
  use_cuda: true
debug_run: true
metrics:
  chosen_timesteps:
    - 0
    - mid-
    - last
metrics_only: false
model:
  agents:
    ag_dropout: 0.0
    cell_type: '<class ''torch.nn.modules.rnn.RNN''>'
    n_bot:
    n_hidden: 20
    n_in: 784
    n_layers: 1
    train_in_out:
      - true
      - true
  connections:
    binarize: false
    comms_dropout: 0.0
    comms_out_scale: 1
    comms_start: last
    global_rewire: false
    sparsity: 0.1
    use_deepR: false
  n_agents: 2
  readout:
    common_readout: true
    n_hid:
    readout_from:
n_tests: 1
optimization:
  agents:
    gamma: 0.95
    lr: 0.001
    reg_readout:
  connections:
    cooling: 0.95
    gamma: 0.95
    gdnoise: 0.001
    global_rewire: false
    l1: 1.0e-05
    lr: 0.001
sweep_id:
task: family
training:
  check_gradients: false
  decision:
    - last
    - all
  early_stop: false
  force_connections: false
  inverse_task: false
  n_epochs: 1
  stopping_acc: 0.95
use_tqdm: 2
varying_params_local: {}
varying_params_sweep: {}
wandb_log: false
